name: 'tab count'

on: push

jobs:

  tabcount:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2
    
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
          echo "${added_modified_file} was changed" and has $(grep -o $'\t' ${added_modified_file} | wc -l) tabs >> log.txt 2>&1 
          done
          
      - uses: actions/upload-artifact@v3
        with:
          name: tabcountlog
          path: ./log.txt

